import = ["/home/tealeaf/.config/alacritty/catppuccin-mocha.toml"]

[cursor.style]
shape = "Beam"

[env]
TERM = "xterm-256color"

[font.normal]
family = "FiraCode Nerd Font Mono"

[window]
decorations = "none"

[window.padding]
x = 2
y = 2
