#!/bin/bash


get_info() {
	status=$(playerctl status) && 
		shuffle=$([ $(playerctl shuffle) == 'On' ] && echo "true" || echo "false") &&
		loop=$(playerctl loop) &&
		playerctl metadata --format "{\"playing\": true, \"title\": \"{{ title }}\", \"art\": \"{{ mpris:artUrl}}\", \"artist\": \"{{ artist }}\", \"album\": \"{{ album }}\", \"position\": \"{{ position }}\", \"length\": \"{{ mpris:length}}\", \"shuffle\": $shuffle, \"loop\": \"$loop\"}" || 
		echo '{"playing": false}'
}


if [[ "$1" == "poll" ]]; then 
	get_info
elif [[ "$1" == "prev" ]]; then
	playerctl previous
elif [[ "$1" == "next" ]]; then
	playerctl next
fi
