"$schema" = 'https://starship.rs/config-schema.json'

add_newline = false
palette = 'catppuccin_macchiato'


format = "$all$directory$character"



[character]
success_symbol = "[](bold green)"

[cmd_duration]
disabled = true

[git_branch]
symbol = ' '
format = '[$symbol$branch(:$remote_branch)]($style) '
style = 'bold lavender'

[git_commit]
tag_symbol = " "

[git_status]
ahead = '↑'
behind = '↓'
untracked = '?'
modified = '!'
staged = '+'
style = 'bold yellow'

[git_metrics]
disabled = false

[package]
disabled = true

[python]
symbol = '󰌠 '

[rust]
symbol = "󱘗 "
style = 'bold peach'

[lua]
symbol = '󰢱 '

[java]
symbol = "󰬷 "

[gradle]
symbol = " "


[palettes.catppuccin_macchiato]
rosewater = "#f4dbd6"
flamingo = "#f0c6c6"
pink = "#f5bde6"
mauve = "#c6a0f6"
red = "#ed8796"
maroon = "#ee99a0"
peach = "#f5a97f"
yellow = "#eed49f"
green = "#a6da95"
teal = "#8bd5ca"
sky = "#91d7e3"
sapphire = "#7dc4e4"
blue = "#8aadf4"
lavender = "#b7bdf8"
text = "#cad3f5"
subtext1 = "#b8c0e0"
subtext0 = "#a5adcb"
overlay2 = "#939ab7"
overlay1 = "#8087a2"
overlay0 = "#6e738d"
surface2 = "#5b6078"
surface1 = "#494d64"
surface0 = "#363a4f"
base = "#24273a"
mantle = "#1e2030"
crust = "#181926"
