"$schema" = 'https://starship.rs/config-schema.json'

add_newline = false
palette = 'catppuccin_macchiato'


format = "$all$directory$character"



[character]
success_symbol = "[](bold green)"

[cmd_duration]
disabled = true

[git_branch]
symbol = ' '
format = '[$symbol$branch(:$remote_branch)]($style) '
style = 'bold lavender'

[git_commit]
tag_symbol = " "

[git_status]
ahead = '↑'
behind = '↓'
untracked = '?'
modified = '!'
staged = '+'
style = 'bold yellow'

[pijul_channel]
symbol = " "

[hg_branch]
symbol = " "

[hostname]
ssh_symbol = " "

[git_metrics]
disabled = false

[directory]
# repo_root_format = "[before_root_path](before_repo_root_style)[repo_root](repo_root_style)[path](style)[read_only](read_only_style) "
repo_root_format = "[ $repo_root]($style)[$path]($style) "
repo_root_style = ""

[directory.substitutions]
'~/git' = 'git'
'~/dev' = 'dev'

[package]
disabled = false
format = "[$symbol$version]($style) "
symbol = "󰏗 "

[python]
symbol = '󰌠 '
format = "[$symbol$pyenv_prefix$version$virtualenv]($style)"

[rust]
symbol = "󱘗 "
style = 'bold peach'
format = "[$symbol($version )]($style)"

[dart]
symbol = " "
format = "[$symbol($version) ]($style)"

[lua]
symbol = '󰢱 '
format = "[$symbol($version )]($style)"

[java]
symbol = "󰬷 "
style = "red dimmed bold"
format = "[$symbol($version )]($style)"

[gradle]
symbol = " "
format = "[$symbol($version )]($style)"

[nodejs]
symbol = "󰎙 "
format = "[$symbol($version )]($style)"

[rlang]
symbol = "󰟔 "
format = "[$symbol($version )]($style)"


[golang]
symbol = "󰟓 "
format = "[$symbol($version )]($style)"

[kotlin]
symbol = "󱈙 "
format = "[$symbol($version )]($style)"

[c]
symbol = "󰙱 "
format = "[$symbol($version(-name) )]($style)"

[docker_context]
symbol = " "
format = "[$symbol$context]($style) "

[dotnet]
symbol = " "
format = "[$symbol($version )(󰓾 tfm )](style)"

[scala]
symbol = " "
format = "[$symbol($version )]($style)"

[bun]
format = "[$symbol($version )]($style)"
symbol = "󱨎 "

[zig]
format = "[$symbol($version )]($style)"

[os.symbols]
Alpaquita = " "
Alpine = " "
Amazon = " "
Android = " "
Arch = " "
Artix = " "
CentOS = " "
Debian = " "
DragonFly = " "
Emscripten = " "
EndeavourOS = " "
Fedora = " "
FreeBSD = " "
Garuda = "󰛓 "
Gentoo = " "
HardenedBSD = "󰞌 "
Illumos = "󰈸 "
Linux = " "
Mabox = " "
Macos = " "
Manjaro = " "
Mariner = " "
MidnightBSD = " "
Mint = " "
NetBSD = " "
NixOS = " "
OpenBSD = "󰈺 "
openSUSE = " "
OracleLinux = "󰌷 "
Pop = " "
Raspbian = " "
Redhat = " "
RedHatEnterprise = " "
Redox = "󰀘 "
Solus = "󰠳 "
SUSE = " "
Ubuntu = " "
Unknown = " "
Windows = "󰍲 "

[palettes.catppuccin_macchiato]
rosewater = "#f4dbd6"
flamingo = "#f0c6c6"
pink = "#f5bde6"
mauve = "#c6a0f6"
red = "#ed8796"
maroon = "#ee99a0"
peach = "#f5a97f"
yellow = "#eed49f"
green = "#a6da95"
teal = "#8bd5ca"
sky = "#91d7e3"
sapphire = "#7dc4e4"
blue = "#8aadf4"
lavender = "#b7bdf8"
text = "#cad3f5"
subtext1 = "#b8c0e0"
subtext0 = "#a5adcb"
overlay2 = "#939ab7"
overlay1 = "#8087a2"
overlay0 = "#6e738d"
surface2 = "#5b6078"
surface1 = "#494d64"
surface0 = "#363a4f"
base = "#24273a"
mantle = "#1e2030"
crust = "#181926"
