gui:
  showIcons: true
  showRandomTip: true
  theme:
    activeBorderColor:
      - "#a6da95" # Green
      - bold
    cherryPickedCommitBgColor:
      - "#8bd5ca" # Teal
    cherryPickedCommitFgColor:
      - "#8aadf4" # Blue
    inactiveBorderColor:
      # - "#cad3f5" # Text
      - "#494d64" # Suface1
    lightTheme: false
    optionsTextColor:
      - "#8aadf4" # Blue
    selectedLineBgColor:
      - "#363a4f" # Surface0
    selectedRangeBgColor:
      - "#363a4f" # Surface0
    unstagedChangesColor:
      - red # Red
notARepository: 'quit'
